# Generated by Django 2.2 on 2019-05-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miseem', '0002_auto_20190511_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[(1, 'pointwise'), (2, 'pairwise'), (3, 'listwise')], max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('belong_to_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='miseem.Question')),
            ],
        ),
    ]
