# Generated by Django 2.2.1 on 2019-05-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miseem', '0024_auto_20190521_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='belong_to_question',
        ),
        migrations.AlterField(
            model_name='answer',
            name='absolute_score',
            field=models.IntegerField(choices=[(66, '6.6'), (36, '3.6'), (74, '7.4'), (84, '8.4'), (41, '4.1'), (2, '0.2'), (90, '9.0'), (17, '1.7'), (77, '7.7'), (64, '6.4'), (65, '6.5'), (19, '1.9'), (10, '1.0'), (54, '5.4'), (76, '7.6'), (38, '3.8'), (49, '4.9'), (80, '8.0'), (89, '8.9'), (9, '0.9'), (23, '2.3'), (55, '5.5'), (95, '9.5'), (97, '9.7'), (57, '5.7'), (44, '4.4'), (11, '1.1'), (83, '8.3'), (61, '6.1'), (50, '5.0'), (91, '9.1'), (73, '7.3'), (72, '7.2'), (40, '4.0'), (25, '2.5'), (75, '7.5'), (26, '2.6'), (99, '9.9'), (39, '3.9'), (6, '0.6'), (70, '7.0'), (27, '2.7'), (48, '4.8'), (43, '4.3'), (4, '0.4'), (71, '7.1'), (79, '7.9'), (56, '5.6'), (69, '6.9'), (13, '1.3'), (21, '2.1'), (82, '8.2'), (42, '4.2'), (32, '3.2'), (18, '1.8'), (88, '8.8'), (62, '6.2'), (94, '9.4'), (47, '4.7'), (22, '2.2'), (60, '6.0'), (14, '1.4'), (16, '1.6'), (92, '9.2'), (98, '9.8'), (7, '0.7'), (81, '8.1'), (93, '9.3'), (31, '3.1'), (1, '0.1'), (86, '8.6'), (51, '5.1'), (53, '5.3'), (37, '3.7'), (29, '2.9'), (3, '0.3'), (63, '6.3'), (78, '7.8'), (5, '0.5'), (20, '2.0'), (24, '2.4'), (15, '1.5'), (33, '3.3'), (58, '5.8'), (59, '5.9'), (52, '5.2'), (12, '1.2'), (35, '3.5'), (45, '4.5'), (28, '2.8'), (96, '9.6'), (34, '3.4'), (87, '8.7'), (100, '10.0'), (30, '3.0'), (67, '6.7'), (68, '6.8'), (46, '4.6'), (85, '8.5'), (8, '0.8')]),
        ),
        migrations.AlterField(
            model_name='answer',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_sentence', to='miseem.Sentence'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='third',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_sentence', to='miseem.Sentence'),
        ),
    ]
